name: Publish NuGet Package

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '*.csproj'
  workflow_dispatch:  

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
    
    - name: Get current version
      id: get_version
      run: |
        VERSION=$(find . -name "*.csproj" -exec grep -oP '(?<=<Version>).*?(?=</Version>)' {} + | head -n 1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./artifacts
    
    - name: Push to NuGet
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
        --source https://api.nuget.org/v3/index.json \
        --api-key ${{ secrets.NUGET_API_KEY }} \
        --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}